// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: google/analytics/data/v1beta/data.proto

package com.google.analytics.data.v1beta;

public interface ResponseMetaDataOrBuilder extends
    // @@protoc_insertion_point(interface_extends:google.analytics.data.v1beta.ResponseMetaData)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <pre>
   * If true, indicates some buckets of dimension combinations are rolled into
   * "(other)" row. This can happen for high cardinality reports.
   * </pre>
   *
   * <code>bool data_loss_from_other_row = 3;</code>
   * @return The dataLossFromOtherRow.
   */
  boolean getDataLossFromOtherRow();
}
