// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: google/analytics/data/v1alpha/analytics_data_api.proto

package com.google.analytics.data.v1alpha;

public interface BatchRunReportsResponseOrBuilder extends
    // @@protoc_insertion_point(interface_extends:google.analytics.data.v1alpha.BatchRunReportsResponse)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <pre>
   * Individual responses. Each response has a separate report request.
   * </pre>
   *
   * <code>repeated .google.analytics.data.v1alpha.RunReportResponse reports = 1;</code>
   */
  java.util.List<com.google.analytics.data.v1alpha.RunReportResponse> 
      getReportsList();
  /**
   * <pre>
   * Individual responses. Each response has a separate report request.
   * </pre>
   *
   * <code>repeated .google.analytics.data.v1alpha.RunReportResponse reports = 1;</code>
   */
  com.google.analytics.data.v1alpha.RunReportResponse getReports(int index);
  /**
   * <pre>
   * Individual responses. Each response has a separate report request.
   * </pre>
   *
   * <code>repeated .google.analytics.data.v1alpha.RunReportResponse reports = 1;</code>
   */
  int getReportsCount();
  /**
   * <pre>
   * Individual responses. Each response has a separate report request.
   * </pre>
   *
   * <code>repeated .google.analytics.data.v1alpha.RunReportResponse reports = 1;</code>
   */
  java.util.List<? extends com.google.analytics.data.v1alpha.RunReportResponseOrBuilder> 
      getReportsOrBuilderList();
  /**
   * <pre>
   * Individual responses. Each response has a separate report request.
   * </pre>
   *
   * <code>repeated .google.analytics.data.v1alpha.RunReportResponse reports = 1;</code>
   */
  com.google.analytics.data.v1alpha.RunReportResponseOrBuilder getReportsOrBuilder(
      int index);
}
