// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: google/analytics/data/v1alpha/analytics_data_api.proto

package com.google.analytics.data.v1alpha;

public interface BatchRunPivotReportsResponseOrBuilder extends
    // @@protoc_insertion_point(interface_extends:google.analytics.data.v1alpha.BatchRunPivotReportsResponse)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <pre>
   * Individual responses. Each response has a separate pivot report request.
   * </pre>
   *
   * <code>repeated .google.analytics.data.v1alpha.RunPivotReportResponse pivot_reports = 1;</code>
   */
  java.util.List<com.google.analytics.data.v1alpha.RunPivotReportResponse> 
      getPivotReportsList();
  /**
   * <pre>
   * Individual responses. Each response has a separate pivot report request.
   * </pre>
   *
   * <code>repeated .google.analytics.data.v1alpha.RunPivotReportResponse pivot_reports = 1;</code>
   */
  com.google.analytics.data.v1alpha.RunPivotReportResponse getPivotReports(int index);
  /**
   * <pre>
   * Individual responses. Each response has a separate pivot report request.
   * </pre>
   *
   * <code>repeated .google.analytics.data.v1alpha.RunPivotReportResponse pivot_reports = 1;</code>
   */
  int getPivotReportsCount();
  /**
   * <pre>
   * Individual responses. Each response has a separate pivot report request.
   * </pre>
   *
   * <code>repeated .google.analytics.data.v1alpha.RunPivotReportResponse pivot_reports = 1;</code>
   */
  java.util.List<? extends com.google.analytics.data.v1alpha.RunPivotReportResponseOrBuilder> 
      getPivotReportsOrBuilderList();
  /**
   * <pre>
   * Individual responses. Each response has a separate pivot report request.
   * </pre>
   *
   * <code>repeated .google.analytics.data.v1alpha.RunPivotReportResponse pivot_reports = 1;</code>
   */
  com.google.analytics.data.v1alpha.RunPivotReportResponseOrBuilder getPivotReportsOrBuilder(
      int index);
}
