// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: google/analytics/data/v1alpha/data.proto

package com.google.analytics.data.v1alpha;

public interface EntityOrBuilder extends
    // @@protoc_insertion_point(interface_extends:google.analytics.data.v1alpha.Entity)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <pre>
   * A Google Analytics GA4 property id. To learn more, see [where to find your
   * Property
   * ID](https://developers.google.com/analytics/devguides/reporting/data/v1/property-id).
   * </pre>
   *
   * <code>string property_id = 1;</code>
   * @return The propertyId.
   */
  java.lang.String getPropertyId();
  /**
   * <pre>
   * A Google Analytics GA4 property id. To learn more, see [where to find your
   * Property
   * ID](https://developers.google.com/analytics/devguides/reporting/data/v1/property-id).
   * </pre>
   *
   * <code>string property_id = 1;</code>
   * @return The bytes for propertyId.
   */
  com.google.protobuf.ByteString
      getPropertyIdBytes();
}
